Repository SportsEcho/EchoProject-BE, pull requests merged in 2024-02, with the labels that each got.

#141 cart / purchase JPA n+1 문제 해결
  src/main/java/com/sportsecho/common/aop/TimeTraceAop.java
  src/main/java/com/sportsecho/memberProduct/entity/MemberProduct.java
  src/main/java/com/sportsecho/memberProduct/repository/MemberProductRepository.java
  src/main/java/com/sportsecho/memberProduct/service/MemberProductServiceImplV1.java
  src/main/java/com/sportsecho/purchase/entity/Purchase.java
  src/main/java/com/sportsecho/purchase/repository/PurchaseRepository.java
  src/main/java/com/sportsecho/purchase/service/PurchaseServiceImplV1.java
Labels: refactor

#144 백엔드 CD 줄바꿈 오류 해결
  .github/workflows/CD.yml
  src/main/java/com/sportsecho/common/aop/TimeTraceAop.java
Labels: fix

#146 Product Entity OptimisticLock 기능 추가
  src/main/java/com/sportsecho/memberProduct/repository/MemberProductRepository.java
  src/main/java/com/sportsecho/product/dto/ProductRequestDto.java
  src/main/java/com/sportsecho/product/entity/Product.java
  src/main/java/com/sportsecho/purchase/service/PurchaseServiceImplV1.java
  src/test/java/com/sportsecho/hotdeal/service/PurchaseHotdealTest.java
  src/test/java/com/sportsecho/product/ProductTest.java
Labels: enhancement, fix

#147 상품 구매 동시성 제어 테스트 추가
  src/main/java/com/sportsecho/product/controller/ProductController.java
  src/test/java/com/sportsecho/product/ProductTest.java
  src/test/java/com/sportsecho/purchase/service/PurchaseServiceImplV1Test.java
Labels: feature

#148 cart, purchase 쿼리 튜닝
  src/main/java/com/sportsecho/memberProduct/repository/MemberProductRepository.java
  src/main/java/com/sportsecho/memberProduct/service/MemberProductServiceImplV1.java
  src/main/java/com/sportsecho/product/repository/ProductRepository.java
  src/main/java/com/sportsecho/purchase/entity/Purchase.java
  src/main/java/com/sportsecho/purchase/service/PurchaseServiceImplV1.java
  src/main/java/com/sportsecho/purchaseProduct/repository/PurchaseProductRepository.java
Labels: refactor

#154 ProductController 버전 변경 - V2
  src/main/java/com/sportsecho/product/controller/ProductController.java
  src/test/java/com/sportsecho/hotdeal/service/PurchaseHotdealTest.java
Labels: feature
