Repository SportsEcho/EchoProject-BE, pull requests merged in 2024-01, with the labels that each got.

#7 ERD 수정으로 인한 Order, Cart Entity 이름 변경
  src/main/java/com/sportsecho/member/entity/Member.java
  src/main/java/com/sportsecho/memberProduct/controller/MemberProductController.java
  src/main/java/com/sportsecho/memberProduct/entity/MemberProduct.java
  src/main/java/com/sportsecho/memberProduct/repository/MemberProductRepository.java
  src/main/java/com/sportsecho/memberProduct/service/MemberProductService.java
  src/main/java/com/sportsecho/memberProduct/service/MemberProductServiceImplV1.java
  src/main/java/com/sportsecho/product/entity/Product.java
  src/main/java/com/sportsecho/purchase/entity/Purchase.java
Labels: !hotfix

#10 User 도메인 기본 기능 및 Spring Security + Jwt를 이용한 인증/인가 환경 구성
  build.gradle
  src/main/java/com/sportsecho/common/configuration/WebSecurityConfig.java
  src/main/java/com/sportsecho/common/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sportsecho/common/jwt/JwtUtil.java
  src/main/java/com/sportsecho/global/exception/ErrorCode.java
  src/main/java/com/sportsecho/member/controller/MemberController.java
  src/main/java/com/sportsecho/member/dto/MemberRequestDto.java
  src/main/java/com/sportsecho/member/entity/Member.java
  src/main/java/com/sportsecho/member/entity/MemberDetailsImpl.java
  src/main/java/com/sportsecho/member/service/MemberDetailsServiceImpl.java
  src/main/java/com/sportsecho/member/service/MemberService.java
  src/main/java/com/sportsecho/member/service/MemberServiceImpl.java
Labels: feature

#12 !hotfix : 수정 DB반영
  src/main/java/com/sportsecho/global/exception/ErrorCode.java
  src/main/java/com/sportsecho/memberProduct/controller/MemberProductController.java
  src/main/java/com/sportsecho/product/dto/response/ProductResponseDto.java
  src/main/java/com/sportsecho/product/entity/Product.java
  src/main/java/com/sportsecho/purchase/entity/Purchase.java
  src/main/java/com/sportsecho/purchaseProduct/entity/PurchaseProduct.java
Labels: !hotfix

#17 User 도메인 1차 기능구현 코드 Refactoring
  .github/pull_request_template.md
  src/main/java/com/sportsecho/common/configuration/RedisConfig.java
  src/main/java/com/sportsecho/common/dto/ResponseCode.java
  src/main/java/com/sportsecho/common/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sportsecho/common/jwt/JwtUtil.java
  src/main/java/com/sportsecho/common/redis/RedisUtil.java
  src/main/java/com/sportsecho/member/controller/MemberController.java
  src/main/java/com/sportsecho/member/dto/MemberResponseDto.java
  src/main/java/com/sportsecho/member/entity/Member.java
  src/main/java/com/sportsecho/member/mapper/MemberMapper.java
  src/main/java/com/sportsecho/member/service/MemberService.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV1.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV2.java
  src/main/resources/application.yml
Labels: refactoring

#16 Feature/comment
  src/main/java/com/sportsecho/comment/controller/CommentController.java
  src/main/java/com/sportsecho/comment/dto/CommentRequest.java
  src/main/java/com/sportsecho/comment/dto/CommentRequestDto.java
  src/main/java/com/sportsecho/comment/dto/CommentResponse.java
  src/main/java/com/sportsecho/comment/dto/CommentResponseDto.java
  src/main/java/com/sportsecho/comment/entity/Comment.java
  src/main/java/com/sportsecho/comment/exception/CommentErrorCode.java
  src/main/java/com/sportsecho/comment/exception/CommentException.java
  src/main/java/com/sportsecho/comment/repository/CommentRepository.java
  src/main/java/com/sportsecho/comment/service/CommentService.java
  src/main/java/com/sportsecho/game/controller/GameController.java
  src/main/java/com/sportsecho/game/dto/GameRequestDto.java
  src/main/java/com/sportsecho/game/entity/Game.java
  src/main/java/com/sportsecho/game/exception/GameErrorCode.java
  src/main/java/com/sportsecho/game/exception/GameException.java
  src/main/java/com/sportsecho/game/mapper/GameMapper.java
  src/main/java/com/sportsecho/game/service/GameService.java
  src/main/java/com/sportsecho/global/exception/BaseErrorCode.java
  src/main/java/com/sportsecho/global/exception/ErrorCode.java
  src/main/java/com/sportsecho/global/exception/ExternalApiException.java
  src/main/java/com/sportsecho/global/exception/GlobalException.java
  src/main/java/com/sportsecho/global/handler/GlobalExceptionHandler.java
Labels: feature

#18 feat(Product) : 상품 CRUD API 구현
  src/main/java/com/sportsecho/product/ErrorCode/ProductErrorCode.java
  src/main/java/com/sportsecho/product/controller/ProductController.java
  src/main/java/com/sportsecho/product/dto/request/ProductRequestDto.java
  src/main/java/com/sportsecho/product/entity/Product.java
  src/main/java/com/sportsecho/product/mapper/ProductMapper.java
  src/main/java/com/sportsecho/product/repository/ProductRepository.java
  src/main/java/com/sportsecho/product/service/ProductService.java
  src/main/java/com/sportsecho/product/service/ProductServiceImplV1.java
Labels: enhancement

#19 feat(cart) : member product API 구현
  src/main/java/com/sportsecho/memberProduct/controller/MemberProductController.java
  src/main/java/com/sportsecho/memberProduct/dto/MemberProductRequestDto.java
  src/main/java/com/sportsecho/memberProduct/dto/MemberProductResponseDto.java
  src/main/java/com/sportsecho/memberProduct/entity/MemberProduct.java
  src/main/java/com/sportsecho/memberProduct/exception/MemberProductErrorCode.java
  src/main/java/com/sportsecho/memberProduct/mapper/MemberProductMapper.java
  src/main/java/com/sportsecho/memberProduct/repository/MemberProductRepository.java
  src/main/java/com/sportsecho/memberProduct/service/MemberProductService.java
  src/main/java/com/sportsecho/memberProduct/service/MemberProductServiceImplV1.java
Labels: feature

#21 User 도메인 최종 코드 PR
  build.gradle
  src/main/java/com/sportsecho/common/jwt/JwtUtil.java
  src/main/java/com/sportsecho/common/jwt/exception/JwtErrorCode.java
  src/main/java/com/sportsecho/global/adivce/CustomRestAdvice.java
  src/main/java/com/sportsecho/global/exception/ErrorCode.java
  src/main/java/com/sportsecho/member/controller/MemberController.java
  src/main/java/com/sportsecho/member/dto/MemberRequestDto.java
  src/main/java/com/sportsecho/member/dto/MemberResponseDto.java
  src/main/java/com/sportsecho/member/exception/MemberErrorCode.java
  src/main/java/com/sportsecho/member/service/MemberService.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV1.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV2.java
Labels: feature, refactoring

#20 Feature/match
  src/main/java/com/sportsecho/comment/controller/CommentController.java
  src/main/java/com/sportsecho/comment/dto/CommentRequestDto.java
  src/main/java/com/sportsecho/comment/mapper/CommentMapper.java
  src/main/java/com/sportsecho/comment/service/CommentService.java
  src/main/java/com/sportsecho/comment/service/CommentServiceImplV1.java
  src/main/java/com/sportsecho/common/jwt/JwtUtil.java
  src/main/java/com/sportsecho/game/controller/GameController.java
  src/main/java/com/sportsecho/game/dto/GameRequestDto.java
  src/main/java/com/sportsecho/game/mapper/GameMapper.java
  src/main/java/com/sportsecho/game/service/GameService.java
  src/main/java/com/sportsecho/game/service/GameServiceImplV1.java
  src/main/java/com/sportsecho/global/adivce/CustomRestAdvice.java
  src/main/java/com/sportsecho/global/exception/ErrorCode.java
  src/main/java/com/sportsecho/global/exception/ExternalApiException.java
  src/main/java/com/sportsecho/global/handler/GlobalExceptionHandler.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV1.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV2.java
Labels: fix

#22 Feature/hotdeal
  src/main/java/com/sportsecho/hotdeal/controller/HotdealController.java
  src/main/java/com/sportsecho/hotdeal/dto/request/HotdealRequestDto.java
  src/main/java/com/sportsecho/hotdeal/dto/request/UpdateHotdealInfoRequestDto.java
  src/main/java/com/sportsecho/hotdeal/dto/response/HotdealResponseDto.java
  src/main/java/com/sportsecho/hotdeal/entity/Hotdeal.java
  src/main/java/com/sportsecho/hotdeal/exception/HotdealErrorCode.java
  src/main/java/com/sportsecho/hotdeal/exception/HotdealException.java
  src/main/java/com/sportsecho/hotdeal/mapper/HotdealMapper.java
  src/main/java/com/sportsecho/hotdeal/repository/HotdealRepository.java
  src/main/java/com/sportsecho/hotdeal/service/HotdealService.java
  src/main/java/com/sportsecho/hotdeal/service/HotdealServiceImplV1.java
  src/main/java/com/sportsecho/member/entity/MemberRole.java
  src/main/java/com/sportsecho/product/controller/ProductController.java
  src/main/java/com/sportsecho/product/dto/request/ProductRequestDto.java
  src/main/java/com/sportsecho/product/exception/ProductErrorCode.java
  src/main/java/com/sportsecho/product/exception/ProductException.java
  src/main/java/com/sportsecho/product/repository/ProductRepository.java
  src/main/java/com/sportsecho/product/service/ProductServiceImplV1.java
Labels: enhancement

#24 GlobalErrorCode 삭제로 인해 발생한 MemberService 오류 해결
  src/main/java/com/sportsecho/member/exception/MemberErrorCode.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV2.java
Labels: fix

#25 GlobalErrorCode 삭제로 인해 발생한 JwtUtil 오류 해결
  src/main/java/com/sportsecho/common/jwt/JwtUtil.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV1.java
Labels: fix

#26 !HOTFIX : product, hotdeal rename jpa method
  src/main/java/com/sportsecho/hotdeal/repository/HotdealRepository.java
  src/main/java/com/sportsecho/hotdeal/service/HotdealServiceImplV1.java
  src/main/java/com/sportsecho/product/repository/ProductRepository.java
  src/main/java/com/sportsecho/product/service/ProductServiceImplV1.java
Labels: bug, fix

#28 Feature/f emock
  src/main/resources/static/css/TestGame.css
  src/main/resources/static/css/index.css
  src/main/resources/static/images/EchoLogo.jpeg
  src/main/resources/static/images/IMG_1851.JPG
  src/main/resources/static/images/btnG_아이콘원형.png
  src/main/resources/static/images/echologo2.jpeg
  src/main/resources/static/images/free-icon-github-sign-25657.png
  src/main/resources/static/images/gitlogo.png
  src/main/resources/static/images/google.png
  src/main/resources/static/images/kakao원형.png
  src/main/resources/static/images/shopping-cart.png
  src/main/resources/static/images/web_light_rd_na@2x.png
  src/main/resources/static/images/스크린샷 2024-01-04 오후 4.34.42.png
  src/main/resources/static/js/TestGame.js
  src/main/resources/static/js/index.js
  src/main/resources/static/testGame.html
  src/main/resources/templates/index.html
  src/main/resources/templates/oauthLogin.html
  src/main/resources/templates/signup.html
Labels: feature

#30 Feature/product
  build.gradle
  src/main/java/com/sportsecho/global/util/s3/AWSConfig.java
  src/main/java/com/sportsecho/global/util/s3/S3Uploader.java
  src/main/java/com/sportsecho/global/util/s3/controller/FileUploadController.java
  src/main/java/com/sportsecho/global/util/s3/service/FileUploadService.java
  src/main/java/com/sportsecho/product/ErrorCode/ProductErrorCode.java
  src/main/java/com/sportsecho/product/controller/ProductController.java
  src/main/java/com/sportsecho/product/exception/ProductErrorCode.java
  src/main/java/com/sportsecho/product/service/ProductServiceImplV1.java
  src/main/resources/application.yml
Labels: enhancement

#31 Feature/purchase
  src/main/java/com/sportsecho/game/mapper/GameMapper.java
  src/main/java/com/sportsecho/product/entity/Product.java
  src/main/java/com/sportsecho/product/repository/ProductRepository.java
  src/main/java/com/sportsecho/purchase/controller/PurchaseController.java
  src/main/java/com/sportsecho/purchase/dto/PurchaseListResponseDto.java
  src/main/java/com/sportsecho/purchase/dto/PurchaseRequestDto.java
  src/main/java/com/sportsecho/purchase/dto/PurchaseResponseDto.java
  src/main/java/com/sportsecho/purchase/entity/Purchase.java
  src/main/java/com/sportsecho/purchase/exception/PurchaseErrorCode.java
  src/main/java/com/sportsecho/purchase/mapper/PurchaseMapper.java
  src/main/java/com/sportsecho/purchase/repository/PurchaseRepository.java
  src/main/java/com/sportsecho/purchase/service/PurchaseService.java
  src/main/java/com/sportsecho/purchase/service/PurchaseServiceImplV1.java
  src/main/java/com/sportsecho/purchaseProduct/dto/PurchaseProductResponseDto.java
  src/main/java/com/sportsecho/purchaseProduct/entity/PurchaseProduct.java
  src/main/java/com/sportsecho/purchaseProduct/mapper/PurchaseProductMapper.java
  src/main/java/com/sportsecho/purchaseProduct/repository/PurchaseProductRepository.java
Labels: feature

#32 Member 도메인 카카오 로그인 기능 추가
  src/main/java/com/sportsecho/common/jwt/JwtUtil.java
  src/main/java/com/sportsecho/member/controller/MemberController.java
  src/main/java/com/sportsecho/member/dto/KakaoUserInfoDto.java
  src/main/java/com/sportsecho/member/entity/Member.java
  src/main/java/com/sportsecho/member/entity/SocialType.java
  src/main/java/com/sportsecho/member/repository/MemberRepository.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV2.java
  src/main/java/com/sportsecho/member/service/oauth/KakaoService.java
  src/main/resources/application.yml
Labels: feature

#34 Member 도메인 네이버 로그인 기능 추가
  src/main/java/com/sportsecho/common/oauth/OAuthUtil.java
  src/main/java/com/sportsecho/common/oauth/exception/OAuthErrorCode.java
  src/main/java/com/sportsecho/member/controller/MemberController.java
  src/main/java/com/sportsecho/member/dto/KakaoUserInfoDto.java
  src/main/java/com/sportsecho/member/dto/MemberRequestDto.java
  src/main/java/com/sportsecho/member/service/MemberService.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV1.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV2.java
  src/main/java/com/sportsecho/member/service/oauth/KakaoService.java
  src/main/resources/application.yml
Labels: feature, refactoring

#35 Feature/hotdeal
  src/main/java/com/sportsecho/SportsEchoApplication.java
  src/main/java/com/sportsecho/hotdeal/controller/HotdealController.java
  src/main/java/com/sportsecho/hotdeal/dto/response/HotdealResponseDto.java
  src/main/java/com/sportsecho/hotdeal/entity/Hotdeal.java
  src/main/java/com/sportsecho/hotdeal/repository/HotdealRepository.java
  src/main/java/com/sportsecho/hotdeal/scheduler/HotdealScheduler.java
  src/main/java/com/sportsecho/hotdeal/service/HotdealService.java
  src/main/java/com/sportsecho/hotdeal/service/HotdealServiceImplV1.java
  src/main/java/com/sportsecho/product/entity/Product.java
Labels: enhancement

#37 Member 도메인 구글 로그인 기능 추가
  src/main/java/com/sportsecho/common/oauth/OAuthUtil.java
  src/main/java/com/sportsecho/common/oauth/SocialType.java
  src/main/java/com/sportsecho/member/controller/MemberController.java
  src/main/java/com/sportsecho/member/entity/Member.java
  src/main/java/com/sportsecho/member/entity/SocialType.java
  src/main/java/com/sportsecho/member/repository/MemberRepository.java
  src/main/java/com/sportsecho/member/service/MemberService.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV1.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV2.java
  src/main/resources/application.yml
Labels: feature, refactoring

#43 Member 도메인 통합 테스트코드 추가
  build.gradle
  src/main/java/com/sportsecho/common/jwt/exception/JwtErrorCode.java
  src/main/java/com/sportsecho/member/controller/MemberController.java
  src/main/java/com/sportsecho/member/mapper/MemberMapper.java
  src/main/java/com/sportsecho/member/service/MemberService.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV1.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV2.java
  src/test/java/com/sportsecho/SportsEchoApplicationTests.java
  src/test/java/com/sportsecho/member/MemberIntegrationTest.java
  src/test/java/com/sportsecho/member/MemberTest.java
  src/test/java/com/sportsecho/member/MemberTestUtil.java
  src/test/java/com/sportsecho/member/service/MemberServiceTest.java
Labels: feature

#45 refactor : product test
  src/main/java/com/sportsecho/product/dto/request/ProductRequestDto.java
  src/test/java/com/sportsecho/product/service/ProductServiceImplV1TestIntegration.java
Labels: refactor

#47 Feature/comment
  .github/pull_request_template.md
  src/main/java/com/sportsecho/comment/dto/CommentRequestDto.java
  src/main/java/com/sportsecho/comment/entity/Comment.java
  src/main/java/com/sportsecho/comment/service/CommentServiceImplV1.java
  src/main/java/com/sportsecho/game/entity/Game.java
  src/main/java/com/sportsecho/game/mapper/GameMapper.java
  src/test/java/com/sportsecho/comment/CommentTestUtil.java
  src/test/java/com/sportsecho/comment/service/CommentServiceImplV1Test.java
  src/test/java/com/sportsecho/comment/service/CommentTestIntegration.java
  src/test/java/com/sportsecho/game/GameTestUtil.java
Labels: feature

#57 feature: CI 파이프 라인 구축
  .github/workflows/test.yml
  build.gradle
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: good first issue, feature

#68 memberProduct, purchase 테스트 리펙토링, 로직 변경
  src/main/java/com/sportsecho/purchase/exception/PurchaseErrorCode.java
  src/main/java/com/sportsecho/purchase/service/PurchaseServiceImplV1.java
  src/test/java/com/sportsecho/memberProduct/MemberProductTest.java
  src/test/java/com/sportsecho/memberProduct/MemberProductTestUtil.java
  src/test/java/com/sportsecho/memberProduct/service/MemberProductServiceImplV1IntTest.java
  src/test/java/com/sportsecho/purchase/PurchaseTest.java
  src/test/java/com/sportsecho/purchase/PurchaseTestUtil.java
  src/test/java/com/sportsecho/purchase/service/PurchaseServiceImplV1Test.java
Labels: refactor

#72 SpringSecurity public endpoints 및 시간 측정 Aop 추가
  src/main/java/com/sportsecho/common/aop/TimeTraceAop.java
  src/main/java/com/sportsecho/common/configuration/WebSecurityConfig.java
  src/main/java/com/sportsecho/common/oauth/OAuthUtil.java
  src/test/java/com/sportsecho/member/MemberIntegrationTest.java
Labels: feature, fix

#75 cart, purchase dto, 엔티티 수정, time stamp
  src/main/java/com/sportsecho/common/time/TimeStamp.java
  src/main/java/com/sportsecho/memberProduct/dto/MemberProductResponseDto.java
  src/main/java/com/sportsecho/memberProduct/entity/MemberProduct.java
  src/main/java/com/sportsecho/purchase/dto/PurchaseListResponseDto.java
  src/main/java/com/sportsecho/purchase/dto/PurchaseResponseDto.java
  src/main/java/com/sportsecho/purchase/entity/Purchase.java
  src/main/java/com/sportsecho/purchase/mapper/PurchaseMapper.java
  src/main/java/com/sportsecho/purchase/service/PurchaseServiceImplV1.java
  src/main/java/com/sportsecho/purchaseProduct/dto/PurchaseProductResponseDto.java
Labels: fix, refactor

#76 STOMP를 이용한 응원 채팅기능 1차 구현
  .github/workflows/CD.yml
  build.gradle
  src/main/generated/com/sportsecho/comment/entity/QComment.java
  src/main/generated/com/sportsecho/comment/mapper/CommentMapperImpl.java
  src/main/generated/com/sportsecho/game/entity/QGame.java
  src/main/generated/com/sportsecho/game/mapper/GameMapperImpl.java
  src/main/generated/com/sportsecho/hotdeal/entity/QHotdeal.java
  src/main/generated/com/sportsecho/hotdeal/mapper/HotdealMapperImpl.java
  src/main/generated/com/sportsecho/member/entity/QMember.java
  src/main/generated/com/sportsecho/member/mapper/MemberMapperImpl.java
  src/main/generated/com/sportsecho/memberProduct/entity/QMemberProduct.java
  src/main/generated/com/sportsecho/memberProduct/mapper/MemberProductMapperImpl.java
  src/main/generated/com/sportsecho/product/entity/QProduct.java
  src/main/generated/com/sportsecho/product/mapper/ProductMapperImpl.java
  src/main/generated/com/sportsecho/purchase/entity/QPurchase.java
  src/main/generated/com/sportsecho/purchase/mapper/PurchaseMapperImpl.java
  src/main/generated/com/sportsecho/purchaseProduct/entity/QPurchaseProduct.java
  src/main/generated/com/sportsecho/purchaseProduct/mapper/PurchaseProductMapperImpl.java
  src/main/java/com/sportsecho/gamechat/MessageIdGenerator.java
  src/main/java/com/sportsecho/gamechat/Room.java
  src/main/java/com/sportsecho/gamechat/RoomIdGenerator.java
  src/main/java/com/sportsecho/gamechat/RoomRepository.java
  src/main/java/com/sportsecho/gamechat/SocketTextHandler.java
  src/main/java/com/sportsecho/gamechat/WebSocketConfig.java
  src/main/java/com/sportsecho/gamechat/WebSocketInterceptor.java
  src/main/java/com/sportsecho/gamechat/controller/MessageController.java
  src/main/java/com/sportsecho/gamechat/dto/MessageRequestDto.java
  src/main/java/com/sportsecho/gamechat/dto/MessageResponseDto.java
  src/main/java/com/sportsecho/gamechat/service/RoomService.java
Labels: feature

#80 Feature/hotdeal
  src/main/java/com/sportsecho/game/entity/Game.java
  src/main/java/com/sportsecho/hotdeal/controller/HotdealController.java
  src/main/java/com/sportsecho/hotdeal/dto/request/PurchaseHotdealRequestDto.java
  src/main/java/com/sportsecho/hotdeal/dto/response/PurchaseHotdealResponseDto.java
  src/main/java/com/sportsecho/hotdeal/entity/Hotdeal.java
  src/main/java/com/sportsecho/hotdeal/exception/HotdealErrorCode.java
  src/main/java/com/sportsecho/hotdeal/mapper/HotdealMapper.java
  src/main/java/com/sportsecho/hotdeal/repository/HotdealRepository.java
  src/main/java/com/sportsecho/hotdeal/service/HotdealService.java
  src/main/java/com/sportsecho/hotdeal/service/HotdealServiceImplV1.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV2.java
  src/main/java/com/sportsecho/product/entity/Product.java
  src/main/java/com/sportsecho/purchase/mapper/PurchaseMapper.java
  src/main/java/com/sportsecho/purchaseProduct/entity/PurchaseProduct.java
  src/main/resources/application-test.yml
  src/test/java/com/sportsecho/hotdeal/HotdealTest.java
  src/test/java/com/sportsecho/hotdeal/HotdealTestUtil.java
  src/test/java/com/sportsecho/hotdeal/service/HotdealServiceIntegrationTest.java
  src/test/java/com/sportsecho/hotdeal/service/PurchaseHotdealTest.java
  src/test/java/com/sportsecho/member/MemberIntegrationTest.java
Labels: enhancement

#81 swagger 적용
  build.gradle
  src/main/java/com/sportsecho/common/configuration/SwaggerConfig.java
  src/main/java/com/sportsecho/common/configuration/WebSecurityConfig.java
Labels: feature

#82 Google OAuth 로그인 redirect_uri 변경 및 Cors설정 추가
  src/main/java/com/sportsecho/common/configuration/CorsConfig.java
  src/main/java/com/sportsecho/common/oauth/OAuthUtil.java
Labels: enhancement, fix

#84 회원가입 로직 및 Member 테스트코드 변경
  src/main/generated/com/sportsecho/comment/entity/QComment.java
  src/main/generated/com/sportsecho/comment/mapper/CommentMapperImpl.java
  src/main/generated/com/sportsecho/common/time/QTimeStamp.java
  src/main/generated/com/sportsecho/game/entity/QGame.java
  src/main/generated/com/sportsecho/game/mapper/GameMapperImpl.java
  src/main/generated/com/sportsecho/hotdeal/mapper/HotdealMapperImpl.java
  src/main/generated/com/sportsecho/member/entity/QMember.java
  src/main/generated/com/sportsecho/member/mapper/MemberMapperImpl.java
  src/main/generated/com/sportsecho/memberProduct/mapper/MemberProductMapperImpl.java
  src/main/generated/com/sportsecho/product/entity/QProduct.java
  src/main/generated/com/sportsecho/product/mapper/ProductMapperImpl.java
  src/main/generated/com/sportsecho/purchase/entity/QPurchase.java
  src/main/generated/com/sportsecho/purchase/mapper/PurchaseMapperImpl.java
  src/main/generated/com/sportsecho/purchaseProduct/mapper/PurchaseProductMapperImpl.java
  src/main/java/com/sportsecho/member/dto/MemberRequestDto.java
  src/main/java/com/sportsecho/member/exception/MemberErrorCode.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV2.java
  src/main/resources/application.yml
  src/test/java/com/sportsecho/member/MemberTest.java
Labels: fix, refactor

#71 Feature/game scheduler
  build.gradle
  src/main/java/com/sportsecho/game/controller/GameController.java
  src/main/java/com/sportsecho/game/dto/GameResponseDto.java
  src/main/java/com/sportsecho/game/entity/Game.java
  src/main/java/com/sportsecho/game/mapper/GameMapper.java
  src/main/java/com/sportsecho/game/repository/GameRepository.java
  src/main/java/com/sportsecho/game/scheduler/GameScheduler.java
  src/main/java/com/sportsecho/game/service/GameService.java
  src/main/java/com/sportsecho/game/service/GameServiceImplV1.java
  src/main/java/com/sportsecho/game/service/GameServiceImplV2.java
  src/test/java/com/sportsecho/comment/service/CommentTestIntegration.java
  src/test/java/com/sportsecho/game/GameTestUtil.java
Labels: wontfix

#86 !Hotfix : game 도메인 수정에 따른 DB update에러로 hibernate create 긴급 수정
  src/main/resources/application.yml
Labels: !hotfix

#88 cart, purchase 유효성 검사 추가
  src/main/java/com/sportsecho/global/handler/GlobalExceptionHandler.java
  src/main/java/com/sportsecho/memberProduct/controller/MemberProductController.java
  src/main/java/com/sportsecho/memberProduct/dto/MemberProductRequestDto.java
  src/main/java/com/sportsecho/purchase/controller/PurchaseController.java
  src/main/java/com/sportsecho/purchase/dto/PurchaseRequestDto.java
  src/test/java/com/sportsecho/purchase/PurchaseTest.java
Labels: refactor

#89 Feature/game scheduler
  src/main/java/com/sportsecho/game/entity/Game.java
  src/main/java/com/sportsecho/game/scheduler/GameScheduler.java
  src/main/resources/application.yml
  src/test/java/com/sportsecho/game/GameTestUtil.java
Labels: fix

#90 웹소켓 STOMP 적용을 위한 구조 변경
  build.gradle
  src/main/java/com/sportsecho/common/configuration/CorsConfig.java
  src/main/java/com/sportsecho/common/configuration/WebSecurityConfig.java
  src/main/java/com/sportsecho/gamechat/Greeting.java
  src/main/java/com/sportsecho/gamechat/HelloMessage.java
  src/main/java/com/sportsecho/gamechat/WebSocketConfig.java
  src/main/java/com/sportsecho/gamechat/controller/MessageController.java
  src/main/resources/application.yml
  src/main/resources/static/app.js
  src/main/resources/static/css/TestGame.css
  src/main/resources/static/css/comment.css
  src/main/resources/static/css/index.css
  src/main/resources/static/images/EchoLogo.jpeg
  src/main/resources/static/images/IMG_1851.JPG
  src/main/resources/static/images/btnG_아이콘원형.png
  src/main/resources/static/images/echologo2.jpeg
  src/main/resources/static/images/free-icon-github-sign-25657.png
  src/main/resources/static/images/gitlogo.png
  src/main/resources/static/images/google.png
  src/main/resources/static/images/kakao원형.png
  src/main/resources/static/images/shopping-cart.png
  src/main/resources/static/images/web_light_rd_na@2x.png
  src/main/resources/static/images/스크린샷 2024-01-04 오후 4.34.42.png
  src/main/resources/static/index.html
  src/main/resources/static/js/TestGame.js
  src/main/resources/static/js/baseball-comment.js
  src/main/resources/static/js/baseball.js
  src/main/resources/static/js/basketball-comment.js
  src/main/resources/static/js/basketball.js
  src/main/resources/static/js/football-comment.js
  src/main/resources/static/js/football.js
  src/main/resources/static/js/index.js
  src/main/resources/static/main.css
  src/main/resources/static/testGame.html
  src/main/resources/templates/baseball-comment.html
  src/main/resources/templates/baseball.html
  src/main/resources/templates/basketball-comments.html
  src/main/resources/templates/basketball.html
  src/main/resources/templates/football-comment.html
  src/main/resources/templates/football.html
  src/main/resources/templates/index.html
  src/main/resources/templates/oauthLogin.html
  src/main/resources/templates/signup.html
Labels: feature, refactor

#92 purchase toResponseDto mapper로 변경
  src/main/java/com/sportsecho/purchase/dto/PurchaseResponseDto.java
  src/main/java/com/sportsecho/purchase/entity/Purchase.java
  src/main/java/com/sportsecho/purchase/mapper/PurchaseMapper.java
  src/main/java/com/sportsecho/purchase/repository/PurchaseRepository.java
  src/main/java/com/sportsecho/purchase/service/PurchaseServiceImplV1.java
  src/test/java/com/sportsecho/purchase/service/PurchaseServiceImplV1Test.java
Labels: refactor

#93 Feature/hotdeal
  src/main/java/com/sportsecho/hotdeal/dto/request/PurchaseHotdealRequestDto.java
  src/main/java/com/sportsecho/hotdeal/dto/response/HotdealResponseDto.java
  src/main/java/com/sportsecho/hotdeal/mapper/HotdealMapper.java
  src/main/java/com/sportsecho/hotdeal/service/HotdealServiceImplV1.java
  src/main/java/com/sportsecho/purchase/mapper/PurchaseMapper.java
  src/main/java/com/sportsecho/purchase/service/PurchaseServiceImplV1.java
  src/test/java/com/sportsecho/hotdeal/service/PurchaseHotdealTest.java
Labels: enhancement

#94 Game 단건 조회 기능 추가
  src/main/generated/com/sportsecho/comment/entity/QComment.java
  src/main/generated/com/sportsecho/comment/mapper/CommentMapperImpl.java
  src/main/generated/com/sportsecho/common/time/QTimeStamp.java
  src/main/generated/com/sportsecho/game/entity/QGame.java
  src/main/generated/com/sportsecho/game/mapper/GameMapperImpl.java
  src/main/generated/com/sportsecho/hotdeal/entity/QHotdeal.java
  src/main/generated/com/sportsecho/hotdeal/mapper/HotdealMapperImpl.java
  src/main/generated/com/sportsecho/member/entity/QMember.java
  src/main/generated/com/sportsecho/member/mapper/MemberMapperImpl.java
  src/main/generated/com/sportsecho/memberProduct/entity/QMemberProduct.java
  src/main/generated/com/sportsecho/memberProduct/mapper/MemberProductMapperImpl.java
  src/main/generated/com/sportsecho/product/entity/QProduct.java
  src/main/generated/com/sportsecho/product/mapper/ProductMapperImpl.java
  src/main/generated/com/sportsecho/purchase/entity/QPurchase.java
  src/main/generated/com/sportsecho/purchase/mapper/PurchaseMapperImpl.java
  src/main/generated/com/sportsecho/purchaseProduct/entity/QPurchaseProduct.java
  src/main/generated/com/sportsecho/purchaseProduct/mapper/PurchaseProductMapperImpl.java
  src/main/java/com/sportsecho/game/controller/GameController.java
  src/main/java/com/sportsecho/game/dto/GameResponseDto.java
  src/main/java/com/sportsecho/game/exception/GameErrorCode.java
  src/main/java/com/sportsecho/game/service/GameService.java
  src/main/java/com/sportsecho/game/service/GameServiceImplV2.java
Labels: feature

#96 STOMP websocket을 이용한 게임 채팅 기능 구현 완료
  src/main/java/com/sportsecho/common/configuration/WebSecurityConfig.java
  src/main/java/com/sportsecho/common/configuration/WebSocketConfig.java
  src/main/java/com/sportsecho/game/controller/GameController.java
  src/main/java/com/sportsecho/gamechat/Greeting.java
  src/main/java/com/sportsecho/gamechat/HelloMessage.java
  src/main/java/com/sportsecho/gamechat/MessageIdGenerator.java
  src/main/java/com/sportsecho/gamechat/Room.java
  src/main/java/com/sportsecho/gamechat/RoomIdGenerator.java
  src/main/java/com/sportsecho/gamechat/RoomRepository.java
  src/main/java/com/sportsecho/gamechat/SocketTextHandler.java
  src/main/java/com/sportsecho/gamechat/WebSocketInterceptor.java
  src/main/java/com/sportsecho/gamechat/controller/MessageController.java
  src/main/java/com/sportsecho/gamechat/dto/GameChatRequestDto.java
  src/main/java/com/sportsecho/gamechat/dto/GameChatResponseDto.java
  src/main/java/com/sportsecho/gamechat/dto/MessageResponseDto.java
  src/main/java/com/sportsecho/gamechat/service/RoomService.java
Labels: enhancement, feature

#97 SportsEcho V0.0.7 배포
  README.md
  src/main/generated/com/sportsecho/comment/entity/QComment.java
  src/main/generated/com/sportsecho/comment/mapper/CommentMapperImpl.java
  src/main/generated/com/sportsecho/common/time/QTimeStamp.java
  src/main/generated/com/sportsecho/game/entity/QGame.java
  src/main/generated/com/sportsecho/game/mapper/GameMapperImpl.java
  src/main/generated/com/sportsecho/hotdeal/entity/QHotdeal.java
  src/main/generated/com/sportsecho/hotdeal/mapper/HotdealMapperImpl.java
  src/main/generated/com/sportsecho/member/entity/QMember.java
  src/main/generated/com/sportsecho/member/mapper/MemberMapperImpl.java
  src/main/generated/com/sportsecho/memberProduct/entity/QMemberProduct.java
  src/main/generated/com/sportsecho/memberProduct/mapper/MemberProductMapperImpl.java
  src/main/generated/com/sportsecho/product/entity/QProduct.java
  src/main/generated/com/sportsecho/product/mapper/ProductMapperImpl.java
  src/main/generated/com/sportsecho/purchase/entity/QPurchase.java
  src/main/generated/com/sportsecho/purchase/mapper/PurchaseMapperImpl.java
  src/main/generated/com/sportsecho/purchaseProduct/entity/QPurchaseProduct.java
  src/main/generated/com/sportsecho/purchaseProduct/mapper/PurchaseProductMapperImpl.java
  src/main/java/com/sportsecho/common/configuration/WebSecurityConfig.java
  src/main/java/com/sportsecho/common/configuration/WebSocketConfig.java
  src/main/java/com/sportsecho/game/controller/GameController.java
  src/main/java/com/sportsecho/game/dto/GameResponseDto.java
  src/main/java/com/sportsecho/game/exception/GameErrorCode.java
  src/main/java/com/sportsecho/game/service/GameService.java
  src/main/java/com/sportsecho/game/service/GameServiceImplV2.java
  src/main/java/com/sportsecho/gamechat/Greeting.java
  src/main/java/com/sportsecho/gamechat/HelloMessage.java
  src/main/java/com/sportsecho/gamechat/MessageIdGenerator.java
  src/main/java/com/sportsecho/gamechat/Room.java
  src/main/java/com/sportsecho/gamechat/RoomIdGenerator.java
  src/main/java/com/sportsecho/gamechat/RoomRepository.java
  src/main/java/com/sportsecho/gamechat/SocketTextHandler.java
  src/main/java/com/sportsecho/gamechat/WebSocketInterceptor.java
  src/main/java/com/sportsecho/gamechat/controller/MessageController.java
  src/main/java/com/sportsecho/gamechat/dto/GameChatRequestDto.java
  src/main/java/com/sportsecho/gamechat/dto/GameChatResponseDto.java
  src/main/java/com/sportsecho/gamechat/dto/MessageResponseDto.java
  src/main/java/com/sportsecho/gamechat/service/RoomService.java
  src/main/java/com/sportsecho/hotdeal/dto/request/PurchaseHotdealRequestDto.java
  src/main/java/com/sportsecho/hotdeal/dto/response/HotdealResponseDto.java
  src/main/java/com/sportsecho/hotdeal/mapper/HotdealMapper.java
  src/main/java/com/sportsecho/hotdeal/service/HotdealServiceImplV1.java
  src/main/java/com/sportsecho/purchase/dto/PurchaseResponseDto.java
  src/main/java/com/sportsecho/purchase/entity/Purchase.java
  src/main/java/com/sportsecho/purchase/mapper/PurchaseMapper.java
  src/main/java/com/sportsecho/purchase/repository/PurchaseRepository.java
  src/main/java/com/sportsecho/purchase/service/PurchaseServiceImplV1.java
  src/main/resources/static/Screenshot 2024-01-10 at 12.13.56 PM.png
  src/main/resources/static/스크린샷 2024-01-15 오후 8.41.27.png
  src/test/java/com/sportsecho/hotdeal/service/PurchaseHotdealTest.java
  src/test/java/com/sportsecho/purchase/service/PurchaseServiceImplV1Test.java
Labels: cicd

#98 GameChat 입장 메세지 기능 및 채팅 메세지 반환 필드 추가
  src/main/java/com/sportsecho/gamechat/controller/MessageController.java
  src/main/java/com/sportsecho/gamechat/dto/GameChatRequestDto.java
  src/main/java/com/sportsecho/gamechat/dto/GameChatResponseDto.java
  src/main/java/com/sportsecho/member/controller/MemberController.java
  src/main/java/com/sportsecho/member/service/MemberService.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV1.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV2.java
Labels: enhancement, feature

#100 Feature/game scheduler
  src/main/java/com/sportsecho/game/entity/Game.java
  src/main/java/com/sportsecho/game/repository/GameRepository.java
  src/main/java/com/sportsecho/game/scheduler/GameScheduler.java
Labels: fix

#101 클라이언트 예외처리를 위한 JwtExceptionFilter 추가
  src/main/java/com/sportsecho/common/configuration/WebSecurityConfig.java
  src/main/java/com/sportsecho/common/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sportsecho/common/jwt/JwtExceptionFilter.java
  src/main/java/com/sportsecho/common/jwt/JwtUtil.java
  src/main/java/com/sportsecho/common/oauth/OAuthUtil.java
Labels: enhancement, feature

#102 Feature/game scheduler
  src/main/java/com/sportsecho/game/entity/Game.java
  src/main/java/com/sportsecho/game/entity/SportsType.java
  src/main/java/com/sportsecho/game/scheduler/GameScheduler.java
Labels: enhancement

#104 image url 테이블 분리
  src/main/java/com/sportsecho/global/util/s3/controller/FileUploadController.java
  src/main/java/com/sportsecho/global/util/s3/service/FileUploadService.java
  src/main/java/com/sportsecho/hotdeal/dto/response/HotdealResponseDto.java
  src/main/java/com/sportsecho/hotdeal/mapper/HotdealMapper.java
  src/main/java/com/sportsecho/product/dto/request/ProductRequestDto.java
  src/main/java/com/sportsecho/product/dto/response/ProductResponseDto.java
  src/main/java/com/sportsecho/product/entity/Product.java
  src/main/java/com/sportsecho/product/entity/ProductImage.java
  src/main/java/com/sportsecho/product/mapper/ProductMapper.java
  src/main/java/com/sportsecho/product/repository/ProductImageRepository.java
  src/main/java/com/sportsecho/product/service/ProductServiceImplV1.java
  src/test/java/com/sportsecho/product/ProductTest.java
  src/test/java/com/sportsecho/product/ProductTestUtil.java
  src/test/java/com/sportsecho/product/service/ProductServiceImplV1TestIntegration.java
Labels: refactor

#105 Feature/game scheduler
  src/main/java/com/sportsecho/game/controller/GameController.java
  src/main/java/com/sportsecho/game/dto/GameResponseDto.java
  src/main/java/com/sportsecho/game/scheduler/GameScheduler.java
  src/main/java/com/sportsecho/game/service/GameServiceImplV2.java
Labels: enhancement

#106 OAuth 로그인 이슈 해결
  src/main/java/com/sportsecho/common/oauth/OAuthUtil.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV2.java
Labels: bug, fix

#110 SportsEcho V0.0.11 배포
  src/main/java/com/sportsecho/common/configuration/CorsConfig.java
  src/main/java/com/sportsecho/common/configuration/WebSecurityConfig.java
  src/main/java/com/sportsecho/game/entity/Game.java
Labels: cicd

#113 클라이언트 버그로 SpringSecurity public endpoint 긴급추가
  src/main/java/com/sportsecho/common/configuration/WebSecurityConfig.java
  src/main/java/com/sportsecho/hotdeal/controller/HotdealController.java
Labels: bug, fix

#117 refactor(Product) : product 코드 리팩토링
  src/main/java/com/sportsecho/product/controller/ProductController.java
  src/main/java/com/sportsecho/product/dto/request/ProductRequestDto.java
Labels: refactor

#119 Product Admin 검증 코드 리팩터링
  src/main/java/com/sportsecho/common/configuration/WebSecurityConfig.java
  src/main/java/com/sportsecho/member/entity/MemberDetailsImpl.java
  src/main/java/com/sportsecho/product/controller/ProductController.java
  src/main/java/com/sportsecho/product/service/ProductService.java
  src/main/java/com/sportsecho/product/service/ProductServiceImplV1.java
  src/test/java/com/sportsecho/product/service/ProductServiceImplV1TestIntegration.java
Labels: enhancement, refactor

#118 refactor(cart) : MemberProductResponseDto에 상품 이미지 리스트 추가
  src/main/java/com/sportsecho/memberProduct/dto/MemberProductResponseDto.java
  src/main/java/com/sportsecho/memberProduct/mapper/MemberProductMapper.java
Labels: refactor

#123 Product 페이지 조회 검색 키워드 옵션 추가
  src/main/java/com/sportsecho/member/mapper/MemberMapper.java
  src/main/java/com/sportsecho/member/service/MemberServiceImplV2.java
  src/main/java/com/sportsecho/product/controller/ProductController.java
  src/main/java/com/sportsecho/product/repository/ProductRepository.java
  src/main/java/com/sportsecho/product/service/ProductService.java
  src/main/java/com/sportsecho/product/service/ProductServiceImplV1.java
  src/test/java/com/sportsecho/product/service/ProductServiceImplV1TestIntegration.java
Labels: enhancement, feature

#122 refactor(Hotdeal) : Hotdeal 리팩토링
  src/main/java/com/sportsecho/common/configuration/WebSecurityConfig.java
  src/main/java/com/sportsecho/hotdeal/controller/HotdealController.java
  src/main/java/com/sportsecho/hotdeal/dto/request/HotdealRequestDto.java
  src/main/java/com/sportsecho/hotdeal/dto/request/PurchaseHotdealRequestDto.java
  src/main/java/com/sportsecho/hotdeal/dto/request/UpdateHotdealInfoRequestDto.java
  src/main/java/com/sportsecho/hotdeal/entity/Hotdeal.java
  src/main/java/com/sportsecho/hotdeal/service/HotdealService.java
  src/main/java/com/sportsecho/hotdeal/service/HotdealServiceImplV1.java
  src/test/java/com/sportsecho/hotdeal/service/HotdealServiceIntegrationTest.java
Labels: refactor

#125 Feature/cart deleteCart API 로직 변경
  src/main/java/com/sportsecho/common/aop/TimeTraceAop.java
  src/main/java/com/sportsecho/common/configuration/WebSecurityConfig.java
  src/main/java/com/sportsecho/memberProduct/controller/MemberProductController.java
  src/main/java/com/sportsecho/memberProduct/repository/MemberProductRepository.java
  src/main/java/com/sportsecho/memberProduct/service/MemberProductService.java
  src/main/java/com/sportsecho/memberProduct/service/MemberProductServiceImplV1.java
  src/test/java/com/sportsecho/memberProduct/service/MemberProductServiceImplV1IntTest.java
Labels: refactor

#126 Product 성능개선 ProductService V2 추가
  build.gradle
  src/main/java/com/sportsecho/common/configuration/CorsConfig.java
  src/main/java/com/sportsecho/hotdeal/scheduler/HotdealScheduler.java
  src/main/java/com/sportsecho/hotdeal/service/HotdealServiceImplV1.java
  src/main/java/com/sportsecho/product/controller/ProductController.java
  src/main/java/com/sportsecho/product/entity/Product.java
  src/main/java/com/sportsecho/product/repository/ProductQueryRepository.java
  src/main/java/com/sportsecho/product/repository/ProductQueryRepositoryImpl.java
  src/main/java/com/sportsecho/product/repository/ProductRepository.java
  src/main/java/com/sportsecho/product/service/ProductServiceImplV2.java
  src/main/resources/application.yml
  src/test/java/com/sportsecho/hotdeal/service/HotdealServiceIntegrationTest.java
Labels: enhancement, feature, refactor

#129 refactor(purchase) : createAt setter 추가
  src/main/java/com/sportsecho/common/time/TimeStamp.java
  src/main/java/com/sportsecho/hotdeal/service/HotdealServiceImplV1.java
  src/main/java/com/sportsecho/purchase/service/PurchaseServiceImplV1.java
Labels: fix

#131 GameChat 타임존 문제 해결
  src/main/java/com/sportsecho/gamechat/controller/MessageController.java
Labels: fix

#132 사용자 회원가입시 한국어가 입력 가능하도록 패턴 수정
  src/main/java/com/sportsecho/member/service/MemberServiceImplV2.java
Labels: fix, refactor

#134 ❗ 긴급 수정
  src/main/java/com/sportsecho/common/aop/TimeTraceAop.java
  src/main/java/com/sportsecho/purchase/mapper/PurchaseMapper.java
  src/test/java/com/sportsecho/purchase/service/PurchaseServiceImplV1Test.java
Labels: !hotfix

#139 카카오 로그인 redirect_uri 변경
  src/main/java/com/sportsecho/common/oauth/OAuthUtil.java
Labels: fix

#140 Https 적용으로 발생한 버그 긴급 수정
  src/main/java/com/sportsecho/common/oauth/OAuthUtil.java
Labels: !hotfix
